"""
Configuration for Splash Pad Finder Directory
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base Paths
BASE_DIR = Path(__file__).parent
TEMPLATES_DIR = BASE_DIR / "templates"
STATIC_DIR = BASE_DIR / "static"
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "dist"

# Site Configuration — UPDATE SITE_NAME and SITE_URL once domain is registered
SITE_NAME = "Splash Pad Locator"
SITE_DESCRIPTION = "Find splash pads, spray parks, and water play areas near you. Free, family-friendly fun for kids of all ages."
SITE_URL = os.getenv("SITE_URL", "https://splashpadlocator.com")
SITE_AUTHOR = "Splash Pad Locator"

# Airtable Configuration
AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID")
AIRTABLE_TABLE_NAME = os.getenv("AIRTABLE_TABLE_NAME", "SplashPads")
AIRTABLE_BLOG_TABLE_NAME = os.getenv("AIRTABLE_BLOG_TABLE_NAME", "Blog Posts")

# US States for state-based pages
US_STATES = [
    {"name": "Alabama", "slug": "alabama", "abbr": "AL",
     "description": "Alabama's long, humid summers create genuine demand for water play from April through September, and the state's communities have responded with a growing network of splash pads and spray parks. Birmingham leads the way with multiple community splash pads distributed across its park system, giving neighborhoods across Jefferson County access without a long drive. Huntsville has invested in modern aquatic facilities as the city's population has grown, adding spray features to several community parks. Mobile's Gulf Coast location means the heat arrives early and lingers late, and its parks offer water play options that take advantage of the extended season. Montgomery and Tuscaloosa round out the major urban centers with community splash pads and aquatic centers suited to family visits. Most municipal splash pads in Alabama are free of charge, though some aquatic centers attached to recreation facilities charge a small admission fee. The season's peak runs from June through August, when temperatures and humidity both climb into uncomfortable territory. Many Alabama splash pads are paired with playgrounds and covered pavilions, making them an easy full-morning outing for families with young children. Weekday mornings are noticeably less crowded than weekend afternoons, especially at the most popular facilities. Bringing sunscreen, water bottles, and a change of clothes will make the visit more comfortable. Always check with local parks departments before visiting, as hours and opening dates vary."},
    {"name": "Alaska", "slug": "alaska", "abbr": "AK",
     "description": "Alaska's splash pad season is short by any measure, but what the state lacks in season length it makes up for in enthusiasm. From late June through August, communities across southcentral and interior Alaska make the most of the long summer daylight hours, and the warmest stretches — when temperatures in Anchorage and Fairbanks can push into the 70s and occasionally the 80s — send families looking for water play options. Anchorage, the state's largest city, has the most developed splash pad infrastructure, with spray features in several community parks that fill quickly on warm days. Fairbanks, in the interior, experiences some of Alaska's hottest summer temperatures, and its community water play areas are popular when the mercury climbs. Palmer and Wasilla in the Matanuska-Susitna Valley have added facilities suited to the region's growing population. The novelty of a hot day in Alaska should not be underestimated — locals take full advantage of every warm afternoon. Most municipal splash pads are free and operate during park hours, but the season can be unpredictable; some years a cool, wet summer limits attendance significantly. Checking local parks department websites before visiting is especially important in Alaska, where facilities may close or adjust hours based on weather conditions. Bring layers, as temperatures can shift quickly even on sunny days."},
    {"name": "Arizona", "slug": "arizona", "abbr": "AZ",
     "description": "In a state where summer temperatures routinely exceed 110 degrees in the low desert, splash pads are genuinely essential infrastructure — not a luxury amenity. Arizona's cities have invested heavily in water play facilities, and the results are among the most impressive in the country. Phoenix operates an extensive network of free community splash pads through its parks and recreation department, with dozens of locations spread across the metro area. Scottsdale and Tempe have added modern spray parks to their community parks, many with shade structures specifically designed for desert conditions. Tucson, in the Sonoran Desert to the south, offers its own community water play options through Pima County and city parks. The season in Arizona is unusually long by national standards, with many facilities opening as early as March and running through October to capture the full extent of the warm season. The brutal heat of June, July, and August means morning visits — before 10 a.m. — are the most comfortable option. Many Arizona splash pads include generous shade sails and covered seating areas, reflecting an understanding that sun protection is as important as water access in the desert. Most municipal splash pads are free. Bringing water bottles and applying sunscreen before entering the splash area will make a significant difference on the hottest days."},
    {"name": "Arkansas", "slug": "arkansas", "abbr": "AR",
     "description": "Arkansas summers are hot and humid, with temperatures regularly reaching the high 90s from June through August across the lowlands and river valleys. The state has expanded its splash pad offerings steadily in recent years, giving families across the Natural State more water play options than ever before. Little Rock anchors the state's splash pad network with multiple community facilities managed by city and county parks departments, including modern spray features that attract families from across the metro area. Fayetteville and the wider Northwest Arkansas region — one of the fastest-growing corners of the country — has seen significant investment in community parks and water play, with Bentonville and Rogers both adding facilities in recent years. Hot Springs, with its long tradition of tourism and recreation, offers water play options that complement the area's resort character. Fort Smith, near the Oklahoma border, has its own community splash pads serving the Arkansas River Valley. Most municipal splash pads in Arkansas are free of charge and operate from Memorial Day through Labor Day. The Ozarks region in the north tends to be slightly cooler than the lowlands, but summer heat is still significant enough to make water play very popular. Weekday mornings are the least crowded times at most facilities. Bringing sunscreen and insect repellent is advisable, as Arkansas summers can be both sunny and buggy."},
    {"name": "California", "slug": "california", "abbr": "CA",
     "description": "California's sheer geographic variety means splash pad seasons vary dramatically from one region to another. In San Diego, where the climate is mild year-round, some facilities operate continuously, while communities in the inland Central Valley — where summer temperatures in Fresno and Bakersfield routinely top 105 degrees — see their splash pads become critical cooling resources from May through October. Los Angeles operates spray features in community parks across its sprawling park system, giving urban families access without venturing far from their neighborhoods. The Bay Area's milder coastal climate tempers demand compared to inland California, but communities in the East Bay and South Bay have invested in water play areas suited to their warm summers. Sacramento and the surrounding suburbs have expanded their splash pad offerings as the region's population has grown. Northern California communities, including Redding and Chico, face intense summer heat and have developed aquatic facilities accordingly. Most California municipal splash pads are free, though some aquatic centers charge admission. The wide variation in climate and local policy means checking specific facility websites before visiting is especially important. On the hottest days, arriving in the morning gives families the best experience. Sun protection — sunscreen, hats, and shade-seeking — is essential throughout the state's inland and desert regions."},
    {"name": "Colorado", "slug": "colorado", "abbr": "CO",
     "description": "Colorado's high-altitude sunshine makes water play a more urgent need than the state's dry climate might suggest. Even on days when temperatures seem moderate, the intensity of UV radiation at elevation means time outdoors can feel much more draining than in lower-altitude states. Denver's parks and recreation department operates splash pads in numerous community parks across the city, serving families in neighborhoods from Stapleton to Wash Park. The suburban communities along the Front Range — Aurora, Lakewood, Arvada, Westminster, and Thornton — have invested in modern spray parks that complement their community recreation centers. Colorado Springs has developed aquatic facilities suitable for the region's large military and family population. Fort Collins, with its strong park culture, offers community splash pads that draw crowds through the summer. The season along the Front Range typically runs from late May through September, with July and August being the busiest months. Colorado's afternoon thunderstorm pattern means morning visits are generally smarter than afternoon trips. Most municipal splash pads are free of charge; some recreation centers charge admission for access to their broader aquatic facilities. Sunscreen is non-negotiable at Colorado's elevation, and bringing water is always a good idea even at a water play facility."},
    {"name": "Connecticut", "slug": "connecticut", "abbr": "CT",
     "description": "Connecticut packs a genuinely impressive number of splash pads into its relatively small footprint, and the quality of the state's community water play facilities reflects the region's investment in parks and recreation. Hartford has developed free spray features in several city parks, giving families in the capital region affordable water play options through the summer. New Haven and Bridgeport have invested in community aquatic facilities that include splash pad zones alongside traditional pool amenities. Stamford and Greenwich, in the southwestern corner of the state nearest to New York City, offer well-maintained community splash pads that attract local families and visitors alike. Manchester, Meriden, and other mid-sized Connecticut cities have added modern spray parks to their parks systems in recent years. The season runs from Memorial Day through Labor Day, occasionally stretching into mid-September during warm autumns. Connecticut's coastal humidity makes summer days feel hotter than the thermometer indicates, making a splash pad a genuine relief on July and August afternoons. Most municipal splash pads in Connecticut are free, though some larger aquatic centers charge a modest admission fee. Weekday mornings are the best times to visit popular facilities, as weekend afternoons can get quite crowded during peak summer weeks. Checking the local parks department website for current hours is always recommended before making the trip."},
    {"name": "Delaware", "slug": "delaware", "abbr": "DE",
     "description": "Delaware may be the nation's second-smallest state, but its communities take summer recreation seriously, and splash pads have become a welcome fixture in parks across the First State. Wilmington, the state's largest city, operates spray features in community parks that serve families throughout New Castle County, with free access during operating hours. Newark, home to the University of Delaware, has invested in community park improvements that include water play areas suited to the city's family-friendly neighborhoods. Dover, the state capital, offers water play options through its parks and recreation department, serving families in Kent County. Rehoboth Beach and the Delaware shore communities attract summer visitors from across the mid-Atlantic region, and some beach-adjacent parks feature spray features alongside their other amenities. The season in Delaware runs from Memorial Day through Labor Day, with peak demand in July and August when mid-Atlantic humidity makes the state's warm temperatures feel particularly intense. Most municipal splash pads in Delaware are free of charge and open to all residents during park hours. Delaware's small size is actually an advantage for families — no community in the state is more than an hour from multiple water play options. Checking local parks department websites is the most reliable way to find current operating hours and seasonal schedules before heading out."},
    {"name": "Florida", "slug": "florida", "abbr": "FL",
     "description": "Florida is genuinely one of the best states in the country for splash pads, and the sheer volume of options reflects a culture built around water and outdoor recreation. The combination of year-round warm weather and a large, family-oriented population has driven investment in water play facilities at every scale, from small neighborhood spray features to elaborate aquatic parks. Orlando and the surrounding communities offer dozens of splash pads, both free municipal options and paid attractions tied to the area's resort and theme park economy. Tampa Bay communities — including Tampa, St. Petersburg, and Clearwater — operate free community splash pads in neighborhood parks throughout the metro area. Jacksonville, the largest city by area in the contiguous United States, has distributed water play facilities across its sprawling park system. Miami-Dade County offers splash pads that operate well into the fall, taking advantage of the region's subtropical climate. Many Florida splash pads operate year-round or close only during the mildest winter months. The summer rainy season, which runs roughly June through September, brings daily afternoon thunderstorms that can interrupt outdoor plans — morning visits are the safest bet. Most municipal splash pads are free. Always check local parks department websites for hours, as facilities in Florida often have specific operating schedules."},
    {"name": "Georgia", "slug": "georgia", "abbr": "GA",
     "description": "Georgia's hot, humid summers create strong and sustained demand for water play across the state, and communities from the mountains to the coast have responded with a growing network of splash pads and aquatic facilities. Metro Atlanta leads the state in both quantity and variety — Fulton, DeKalb, Gwinnett, and Cobb counties have all invested in community splash pads that serve suburban and urban families throughout the region. The city of Atlanta itself operates spray features in several parks, offering free water play in neighborhoods across the city. Savannah, with its coastal humidity and historic park squares, has added splash pad options that suit the city's character. Augusta and Columbus, as major mid-sized cities, each offer community aquatic facilities with spray features. The season in Georgia runs from April through September at many facilities, with the peak from June through August. Summer heat in Georgia is genuine and unrelenting — temperatures in the high 90s paired with humidity that makes conditions feel well above 100 degrees are common through July and August. Shade and seating near the splash area are important amenities to look for when choosing a facility. Most municipal splash pads in Georgia are free of charge. Weekend afternoons are the busiest times at popular facilities; weekday mornings offer a more relaxed experience. Sunscreen, water bottles, and a change of clothes are standard gear for Georgia splash pad visits."},
    {"name": "Hawaii", "slug": "hawaii", "abbr": "HI",
     "description": "Hawaii's tropical climate means water play is a year-round possibility, and while the islands are internationally recognized for their beaches, splash pads have found a meaningful place in community parks across the state. On Oahu, which is home to the majority of Hawaii's population, community parks in Honolulu and surrounding municipalities offer spray features that give families a sheltered alternative to the beach — particularly useful for parents of very young children who benefit from the shallower, controlled water play environment. The Windward and Leeward sides of Oahu offer different microclimates, but both experience the kind of warm, humid conditions that make water play appealing year-round. Maui's growing communities, particularly around Kahului and Kihei, have developed park facilities that include water play options. The Big Island's diverse climate zones mean some areas, particularly around Kailua-Kona on the dry western coast, are especially well-suited to splash pad visits. Most community splash pads in Hawaii are free and open to the public during park hours. Hawaii's near-constant UV intensity means sunscreen is absolutely essential, even on overcast days. Visiting early in the morning is recommended to avoid both the midday heat and peak crowd times. The state's tourist economy means some water play facilities near resort areas may have different access arrangements than purely municipal parks."},
    {"name": "Idaho", "slug": "idaho", "abbr": "ID",
     "description": "Idaho's summers are drier and often hotter than visitors expect, especially in the southern valleys and the Treasure Valley around Boise. The combination of desert heat and abundant sunshine makes splash pads a valued community amenity across the state. Boise leads the state with the most developed splash pad infrastructure, with the Boise Parks and Recreation department operating water play facilities in multiple community parks across the city and its suburbs, including Nampa and Meridian. Meridian in particular has seen rapid population growth and has invested in modern community parks that include spray features well-suited to family visits. Twin Falls, situated near the Snake River Canyon, offers community water play options that serve the families of south-central Idaho. Coeur d'Alene, in the northern Panhandle, has a slightly different climate — more Pacific Northwest than high desert — but still sees warm enough summers to make splash pads worthwhile. The season statewide typically runs from June through early September, with peak demand in July and August when temperatures in the Treasure Valley can exceed 100 degrees. Most municipal splash pads in Idaho are free of charge. Mornings before 11 a.m. are the most comfortable visiting times during peak summer heat. Sunscreen, water, and sandals or water shoes are the practical essentials for an Idaho splash pad visit."},
    {"name": "Illinois", "slug": "illinois", "abbr": "IL",
     "description": "Illinois has one of the deepest splash pad networks in the Midwest, driven by the Chicago Park District's extensive investment in neighborhood water play and the steady development of suburban aquatic facilities across the collar counties. Chicago itself operates spray features and water play zones in dozens of parks across all 77 community areas, giving urban families free access to water play within walking distance of most neighborhoods. The northern suburbs — communities like Evanston, Naperville, and Wheaton — have built modern community splash pads that draw families throughout the summer. DuPage, Lake, Kane, and Will counties all feature multiple facilities ranging from free neighborhood spray parks to full aquatic centers with admission fees. Downstate Illinois is well-represented too: Peoria, Springfield, Rockford, and Champaign-Urbana all operate community water play facilities that serve their regions. The season across most of Illinois runs from Memorial Day through Labor Day, with July and August being the busiest months. Illinois summers bring genuine heat and humidity, particularly in the Chicago metro and central Illinois, with temperatures frequently climbing into the 90s. Most municipal splash pads in Chicago and the suburbs are free. For the largest facilities, arriving before 10 a.m. on weekends is the best strategy for finding open space. Always check the Chicago Park District or local parks department website for current schedules and any seasonal closures."},
    {"name": "Indiana", "slug": "indiana", "abbr": "IN",
     "description": "Indiana's parks departments have made splash pads a summer priority across the Hoosier State, and the result is a solid network of community water play options serving families from Gary to Evansville. Indianapolis anchors the state with the most options — Indy Parks operates spray features in neighborhoods throughout the city, and Hamilton County communities like Carmel and Fishers have built some of the state's most modern and well-equipped splash pad facilities. Fort Wayne, the state's second-largest city, has invested in community aquatic amenities that include splash pad zones with features suited to a range of ages. South Bend, Bloomington, and Muncie each offer community water play options through their parks and recreation departments. The season in Indiana runs from Memorial Day through Labor Day, with July and August being the peak months for attendance. Indiana summers are genuinely hot and humid — the Ohio River Valley in the south tends to be particularly steamy — making a well-maintained splash pad a meaningful relief for families on summer afternoons. Most municipal splash pads in Indiana are free of charge, though some recreation center aquatic facilities charge admission. Weekend mornings are the best time to visit popular facilities before the afternoon crowds arrive. Sunscreen, a towel, and a change of clothes are the practical basics for any Indiana splash pad outing."},
    {"name": "Iowa", "slug": "iowa", "abbr": "IA",
     "description": "Iowa's splash pads and community aquatic facilities are genuine gathering places during the summer months, and the quality of the state's parks investment shows across both its cities and smaller communities. Des Moines has the most developed splash pad network in the state, with the city's parks department operating free spray features in neighborhoods across the metro and suburban communities like West Des Moines and Ankeny adding their own facilities. Cedar Rapids has similarly invested in community water play, with parks that pair splash pads with playgrounds and picnic amenities for a complete family outing. Davenport and the Quad Cities area, along the Mississippi River, offer water play options that serve both Iowa and Illinois families. Waterloo, Iowa City, and Sioux City round out the state's major urban centers with their own community aquatic amenities. The season typically runs from late May through Labor Day, with July and August bringing the most intense heat and humidity. Iowa summers can be surprisingly hot, with temperatures reaching the mid-90s and humidity that pushes heat index values well above 100 degrees during peak weeks. Most municipal splash pads in Iowa are free and operated during park hours without admission. Arriving on weekday mornings gives families the most relaxed experience at the most popular locations. Sunscreen and water bottles are practical necessities for any summer outing in Iowa's open, sun-exposed parks."},
    {"name": "Kansas", "slug": "kansas", "abbr": "KS",
     "description": "Kansas summers are hot, often dry, and frequently windy, and the state's communities have built quality splash pads and aquatic facilities to help families cool off during the long warm season. Wichita leads the state with the most diverse collection of water play options, including free community splash pads in city parks and larger paid aquatic centers with multiple features. The city's park system serves families across south-central Kansas and draws visitors from the surrounding region. Overland Park and Olathe, in the Kansas City metro's Kansas portion, have invested heavily in modern community parks and recreation facilities that include well-designed splash pads popular with suburban families. Lawrence, home to the University of Kansas, offers community water play that reflects the college town's focus on family-friendly recreation. Topeka, the state capital, has community splash pads that serve central Kansas families through the summer months. The season typically runs from Memorial Day through Labor Day, with July being the most intense month for both heat and demand. Kansas is known for strong summer storms that can develop quickly, so checking the weather before heading out is a good habit. Most municipal splash pads across Kansas are free. Many facilities include shaded pavilion seating, which is a welcome feature in a state where the sun is intense and shade trees are not always abundant. Weekday mornings offer the least crowded visiting experience."},
    {"name": "Kentucky", "slug": "kentucky", "abbr": "KY",
     "description": "Kentucky's warm, humid summers create steady demand for water play across the Bluegrass State, and the state's communities have developed a growing collection of splash pads and aquatic facilities that serve families from Appalachia to the Purchase region. Louisville anchors Kentucky's splash pad offerings with the most diverse selection in the state — the city's Metro Parks department operates spray features in community parks serving Louisville's sprawling urban and suburban neighborhoods, with several facilities offering free access. Lexington, the second-largest city, has invested in community aquatic facilities that include modern splash pad zones suited to the Fayette County family population. Bowling Green, a growing mid-sized city in south-central Kentucky, has expanded its parks and recreation options to include splash pad facilities. Northern Kentucky communities across the river from Cincinnati — including Covington and Florence — have developed water play options that complement the broader Cincinnati metro's aquatic offerings. The season runs from May through September, with the peak from June through August when Kentucky's river valley humidity makes conditions feel especially intense. Most municipal splash pads in Kentucky are free of charge. Many are paired with playgrounds and pavilion seating, making them well-suited to half-day family outings. Arriving on weekday mornings is the most relaxed visiting strategy. Always check local parks department websites for current seasonal hours."},
    {"name": "Louisiana", "slug": "louisiana", "abbr": "LA",
     "description": "Louisiana's climate is among the most challenging in the country for outdoor summer activity — heat and humidity combine to create conditions where a splash pad isn't just pleasant, it's a genuine public health benefit. The state's communities have responded with water play options that take advantage of Louisiana's long warm season, which can stretch from March through October in the southern parishes. Baton Rouge has developed one of the state's strongest municipal splash pad networks, with free community spray parks in city parks across East Baton Rouge Parish that serve families throughout the summer. New Orleans, with its distinctive neighborhood culture, has invested in community parks that include splash pads, though flooding-related park challenges require checking current facility status. Lafayette, in Acadiana, offers community water play options that reflect the region's investment in outdoor recreation. Shreveport and Monroe serve north Louisiana families with aquatic facilities suited to the region's hot summers. Most municipal splash pads in Louisiana are free, though some aquatic centers charge admission. The summer rainy season means afternoon thunderstorms are a near-daily occurrence from June through September, making morning visits the most reliable choice. Insect repellent is worth adding to the bag alongside sunscreen, particularly in areas near water. Check local parks departments for current hours and seasonal schedules, which can vary significantly across the state."},
    {"name": "Maine", "slug": "maine", "abbr": "ME",
     "description": "Maine's summer season is shorter than almost any other state's, but the communities that have invested in splash pads treat them as genuine seasonal treasures that families look forward to all year. The season typically runs from mid-June through mid-August, occasionally extending to Labor Day during warm years, giving families a compact but enthusiastic window of water play. Portland, Maine's largest city, anchors the state's splash pad options with facilities in community parks that serve the Greater Portland metro and draw visitors from surrounding towns. Bangor, in central Maine, offers community water play options through its parks and recreation department that serve families across Penobscot County. The Lewiston-Auburn metro area has invested in community aquatic facilities that reflect the region's family-focused parks programs. Coastal communities like Saco and Biddeford, which attract summer visitors, have added water play features to their parks. Maine summers can be genuinely warm and humid — when the heat arrives in late July, a splash pad becomes one of the most popular destinations in any community. Most municipal splash pads in Maine are free of charge. Because the season is short, popular facilities fill up quickly on the hottest days, and weekday mornings are the most relaxed visiting option. Checking local parks department websites for opening dates is essential, as Maine facilities often have the shortest predictable operating windows of any New England state."},
    {"name": "Maryland", "slug": "maryland", "abbr": "MD",
     "description": "Maryland's humid mid-Atlantic summers drive consistent demand for water play, and the state's diverse communities have built an impressive range of splash pads and aquatic facilities to serve families from the mountains to the Chesapeake Bay. The Baltimore metro leads the state in volume — the city's recreation and parks department operates spray features in community parks across Baltimore's neighborhoods, and surrounding counties including Baltimore County, Howard County, and Anne Arundel County have all invested in modern community splash pad facilities. Montgomery County, in the Washington D.C. suburbs, has one of the strongest aquatic recreation programs in the region, with multiple community splash pads and aquatic centers serving the county's large, family-oriented population. Prince George's County similarly offers community water play options that serve families across the suburban Washington corridor. On the Eastern Shore, communities like Annapolis and Ocean City-area parks offer splash pad options suited to their summer visitor populations. The season runs from Memorial Day through Labor Day, with the peak from late June through August when Maryland's coastal humidity makes conditions feel especially warm. Most municipal splash pads are free, though some county aquatic centers charge admission. Weekday mornings are consistently the least crowded visiting times. Always verify hours with local parks departments before visiting, as Maryland facility schedules vary widely by county and municipality."},
    {"name": "Massachusetts", "slug": "massachusetts", "abbr": "MA",
     "description": "Massachusetts communities take their splash pads seriously, and the investment shows across the Commonwealth. Boston's extensive parks system operates spray decks in neighborhood parks from Jamaica Plain to East Boston, giving urban families easy access without a long drive. Suburban towns across Greater Boston — from the South Shore to the MetroWest region — have added dedicated splash pad facilities to their community parks, many of them free and open to all residents. The season typically runs from late June through Labor Day, though some facilities open as early as Memorial Day during warm springs. New England's humidity can make summer days in Massachusetts feel hotter than the thermometer suggests, making a shaded splash pad with nearby seating a genuine relief for parents and kids alike. Beyond the Boston metro, communities in the Pioneer Valley, Cape Cod, and the North Shore offer their own water play options. Many splash pads are paired with traditional playgrounds, picnic areas, and walking paths, making them an ideal all-day outing. Weekday mornings are generally the least crowded times to visit. Most municipal splash pads are free of charge, though some aquatic centers charge a small admission fee. Always check local parks department websites for seasonal opening dates and hours, as they vary by municipality."},
    {"name": "Michigan", "slug": "michigan", "abbr": "MI",
     "description": "Michigan's position between four of the five Great Lakes gives it a distinctive summer climate — warm, occasionally humid, and enthusiastically embraced by residents who understand what a long winter means for summer recreation. The state has developed a strong splash pad network that serves both peninsulas, with Detroit and the metro area leading in volume. Detroit's city parks and suburban communities throughout Wayne, Oakland, and Macomb counties offer free and paid water play options at various scales, from neighborhood spray pads to full aquatic centers. Grand Rapids, Michigan's second-largest city, has invested in community parks that include modern splash pad facilities serving families across Kent County and the surrounding region. Lansing and East Lansing, home to Michigan State University, offer community water play options with a college-town sensibility. Traverse City, a popular northern Michigan destination, and communities throughout the Petoskey area and the Upper Peninsula bring water play options to summer tourists and year-round residents alike. The season typically runs from Memorial Day through Labor Day in Lower Michigan, with the Upper Peninsula's shorter warm season compressing operations to June through August. Most municipal splash pads in Michigan are free of charge. Lake Michigan's western shore draws substantial summer tourism, and communities like Muskegon and Holland offer water play facilities that complement beach access. Weekday mornings at popular facilities are significantly less crowded than weekend afternoons."},
    {"name": "Minnesota", "slug": "minnesota", "abbr": "MN",
     "description": "Minnesota's summer arrives decisively and Minnesotans embrace it with equal decisiveness — and splash pads are a central part of that summer enthusiasm. The Twin Cities metro leads the state with the most robust splash pad network, with Minneapolis and St. Paul operating spray features in community parks across both cities through the Minneapolis Park and Recreation Board and St. Paul Parks and Recreation departments. Suburban communities in Hennepin, Ramsey, Dakota, and Washington counties have invested in modern spray parks that draw consistent crowds through the season. Rochester, home to the Mayo Clinic, has developed community parks with water play suited to its family-oriented population. Duluth, on the western end of Lake Superior, has a cooler microclimate than the Twin Cities but still offers community water play options during its warm summer months. St. Cloud and Mankato anchor central and southern Minnesota with their own community aquatic facilities. The season runs from mid-June through mid-August at most Minnesota facilities, with some extending to Labor Day. Minnesota's summer humidity can make July and August feel significantly hotter than the actual temperature, making a splash pad a genuine relief on peak summer days. Most municipal splash pads are free of charge. Weekday mornings are the least crowded option at popular facilities. Always check local parks department websites for current seasonal hours, as Minnesota facilities often have specific opening and closing windows tied to lifeguard staffing."},
    {"name": "Mississippi", "slug": "mississippi", "abbr": "MS",
     "description": "Mississippi's summers are long, hot, and intensely humid — conditions that make water play not just appealing but genuinely necessary for outdoor family time from late spring through early fall. The state's communities are steadily adding splash pads and spray features to their parks, and the pace of investment has increased as residents recognize the public benefit of free or affordable water play. Jackson, the state capital, has community parks with splash pad facilities that serve metro area families throughout the extended summer season. Gulfport and Biloxi on the Gulf Coast offer a more tourist-oriented set of water play options, with coastal humidity and warm temperatures that make the season unusually long — April through October is a realistic operational window. Hattiesburg serves south-central Mississippi families with community aquatic options, while Tupelo anchors water play access in the northeastern corner of the state. Most municipal splash pads in Mississippi are free of charge, reflecting the community-focused investment in parks across the state. The summer heat peaks in July and August, when daytime temperatures in the mid-to-upper 90s combined with humidity push heat index values well above 100 degrees. Morning visits — before 10 a.m. — are the most comfortable choice during peak summer weeks. Sunscreen, insect repellent near wooded parks, and water bottles are the practical essentials for a Mississippi splash pad outing. Local parks departments are the best source for current hours and seasonal schedules."},
    {"name": "Missouri", "slug": "missouri", "abbr": "MO",
     "description": "Missouri's position at the geographic heart of the country means it gets the full force of Midwestern summer — heat, humidity, and the kind of sticky August days that make a splash pad one of the most appealing destinations in any community. The state's two major metros anchor the splash pad network on both ends. Kansas City operates spray features and community aquatic facilities through its parks system, and suburban communities throughout Johnson and Clay counties have invested in modern splash pads that serve the Missouri suburbs of the metro area. St. Louis offers free community splash pads through its city parks department, and St. Louis County communities including Chesterfield, Ballwin, and Kirkwood have developed their own facilities with features suited to family visits. Columbia, home to the University of Missouri and one of the state's fastest-growing mid-sized cities, has community splash pads that reflect the city's parks investment. Springfield serves southwest Missouri families with aquatic facilities appropriate to the Ozarks region. The season runs from Memorial Day through Labor Day across most of Missouri, with the peak demand falling in July and August when temperatures in the Kansas City and St. Louis metros frequently reach the mid-90s alongside oppressive humidity. Most municipal splash pads in Missouri are free. Some larger recreation center aquatic facilities charge admission. Weekday mornings are the least crowded times to visit. Checking local parks department websites for current hours is recommended, as schedules can change throughout the season."},
    {"name": "Montana", "slug": "montana", "abbr": "MT",
     "description": "Montana's reputation for dramatic scenery and outdoor adventure sometimes overshadows the practical reality of its summers: the valleys and plains can get genuinely hot, and families are grateful for any water play option within reach. Billings, the state's largest city, leads Montana's splash pad network with community aquatic facilities that serve the Yellowstone Valley region and draw visitors from the surrounding area. Missoula, anchored by the University of Montana and a strong outdoor recreation culture, has community splash pad facilities that reflect the city's parks investment and suit its family-friendly character. Great Falls and Helena, the state capital, offer community water play options through their parks and recreation departments. Bozeman, one of Montana's fastest-growing communities, has added splash pad facilities to keep pace with its expanding family population. The season typically runs from mid-June through August, capturing the core of Montana's mountain summer. July and August in the valleys can bring temperatures well into the 90s with lower humidity than most of the country, making the heat feel intense without the heaviness of the South or Midwest. Many Montana splash pads are free and operated by city parks departments during park hours. Because facilities are fewer and more spread out than in more densely populated states, verifying that a specific location is open before making a long drive is particularly worthwhile. Sunscreen is essential in Montana's high-altitude, clear-sky summer sun."},
    {"name": "Nebraska", "slug": "nebraska", "abbr": "NE",
     "description": "Nebraska's communities have invested steadily in splash pads and aquatic centers to combat the state's hot, humid summers, and the results are felt statewide. Omaha leads with multiple community splash pads spread across its parks system, serving families in neighborhoods throughout the metro. Lincoln's parks and recreation department has similarly expanded water play options, with facilities that draw consistent crowds through the summer months. Beyond the two major cities, mid-sized communities including Kearney, Norfolk, Grand Island, and Hastings have developed their own splash pad facilities, reflecting the broad community commitment to outdoor recreation across Nebraska. The season typically runs from Memorial Day through Labor Day, though peak attendance comes in July and August when temperatures and humidity peak on the Great Plains. The state's continental climate means summers can bring extended stretches of 90-degree days, making community water play especially welcome. Most municipal splash pads in Nebraska are free of charge and open to all residents, operating during park hours. Many are positioned alongside playgrounds and picnic shelters, making them a complete family outing. Arriving early on weekday mornings is the best strategy for avoiding weekend crowds at the most popular locations. Some larger aquatic centers combine splash pads with pools and slides and may charge admission."},
    {"name": "Nevada", "slug": "nevada", "abbr": "NV",
     "description": "Nevada's desert climate makes splash pads something close to essential public infrastructure in the summer months. Las Vegas leads the state and is one of the most splash pad-rich cities in the country relative to its climate needs — the city of Las Vegas, Henderson, and the Clark County park system collectively operate multiple free community splash pads that serve the metropolitan area's large family population. Henderson in particular has invested in community parks with shade structures and spray features designed specifically for the desert environment, where summer temperatures routinely exceed 110 degrees and outdoor activity without water access becomes genuinely dangerous. Summerlin, a large planned community in the western Las Vegas Valley, has several neighborhood splash pads that serve the area's suburban families. North Las Vegas adds to the metro's water play options with its own community facilities. Reno, in northern Nevada, has a different climate — drier and slightly cooler than Las Vegas — but summer temperatures still frequently reach the 90s and above, driving demand for the splash pads available through the city's parks and recreation department. The season in the Las Vegas metro runs from approximately March through October, making it one of the longest operational windows in the country. Most municipal splash pads in Nevada are free. Morning visits, before the full desert heat arrives, are strongly recommended — for comfort and safety alike. Bringing water and applying sunscreen before arriving at the splash area is essential."},
    {"name": "New Hampshire", "slug": "new-hampshire", "abbr": "NH",
     "description": "New Hampshire packs its splash pad season into a relatively compact window, but what the Granite State lacks in season length it compensates for with enthusiastic community investment in outdoor recreation. The season runs from late June through mid-August at most facilities, with some extending to Labor Day during warm summers. Manchester, the state's largest city, has community parks with splash pad features that serve families throughout the southern New Hampshire region. Nashua, near the Massachusetts border, offers community water play options that draw from the broader Merrimack Valley area and reflects the region's strong parks programs. Concord, the state capital, has invested in community aquatic facilities appropriate to its size and population. The Lakes Region — including communities near Lake Winnipesaukee — attracts summer visitors and has developed water play options alongside its other recreation amenities. The White Mountains region, while known primarily for hiking and scenic tourism, has community facilities in its valley towns that serve local families during the summer. New Hampshire's summer humidity can make July and August days feel meaningfully warmer than the thermometer suggests, particularly in the Merrimack Valley and the seacoast region near Portsmouth. Most municipal splash pads in New Hampshire are free of charge, reflecting the state's tradition of community-funded recreation. Because the season is short and popular on warm days, weekday mornings are the best time to visit without competition for space. Checking local parks department websites for opening dates and hours is especially important in New Hampshire, where facilities often have precise seasonal windows."},
    {"name": "New Jersey", "slug": "new-jersey", "abbr": "NJ",
     "description": "New Jersey packs a dense network of splash pads into the Garden State, and the variety is genuinely impressive. From the Shore communities — where beachfront spray features attract summer tourists and locals alike — to the North Jersey suburbs close to New York City, the state offers water play at nearly every level of scale and budget. Central Jersey communities have built modern aquatic centers that combine traditional pools with splash pad zones, while South Jersey's residential neighborhoods feature free community spray parks that serve as neighborhood gathering places on hot days. The state's compact geography means most New Jersey families are within a 20-minute drive of at least one splash pad option. The season runs from Memorial Day through September, with the busiest period from late June through mid-August. New Jersey's mid-Atlantic climate brings genuine summer heat and humidity, with temperatures frequently reaching the high 80s and 90s during peak weeks. Most municipal splash pads in the state are free of charge and operate during park hours without advance registration. However, some aquatic centers require small admission fees and may fill quickly on the hottest days, so arriving early or visiting on weekday mornings gives families the best experience. Local parks department websites are the most reliable source for current hours and opening dates."},
    {"name": "New Mexico", "slug": "new-mexico", "abbr": "NM",
     "description": "New Mexico's desert climate brings dry heat and intense high-altitude sunshine that makes water play one of the most sought-after summer activities across the Land of Enchantment. Albuquerque, the state's largest city, anchors New Mexico's splash pad network with community aquatic facilities managed by the city's parks and recreation department, offering free and low-cost water play for families throughout the Bernalillo County area. Rio Rancho, a large and rapidly growing suburb north of Albuquerque, has added community splash pad facilities that serve its expanding family population. Santa Fe, at an elevation of 7,000 feet, has a noticeably cooler summer climate than lower-elevation communities, but the high-altitude sun is intense and splash pads remain popular during the warmest months. Las Cruces, in the southern Mesilla Valley near the Texas border, experiences some of the state's most intense summer heat, and community water play options there reflect the extended season possible in New Mexico's south. Farmington serves families in the Four Corners region with its own community aquatic facilities. The season in most of New Mexico runs from late May through September, with the southern communities enjoying a somewhat longer operational window. New Mexico's monsoon season arrives in July and brings afternoon thunderstorms that can close outdoor splash pads temporarily — morning visits are the safest bet during monsoon months. Most municipal splash pads are free of charge. Sunscreen is essential at New Mexico's elevations, and staying hydrated in the dry desert air is important even when playing in the water."},
    {"name": "New York", "slug": "new-york", "abbr": "NY",
     "description": "New York State offers one of the most diverse and extensive splash pad networks in the country, driven by the sheer scale of New York City's parks investment and the strong parks programs in suburban and upstate communities. The NYC Parks department operates spray showers and water play features in hundreds of parks across all five boroughs, giving urban families free water play access within walking distance in most neighborhoods. The Bronx, Brooklyn, Queens, Manhattan, and Staten Island each have multiple facilities, with Brooklyn's Prospect Park and Queens' Flushing Meadows Corona Park among the most visited. Long Island communities in Nassau and Suffolk counties have built modern community splash pads that serve the region's large suburban family population. Westchester County, immediately north of the city, has a strong parks program with spray features and aquatic facilities across multiple communities. Upstate, Albany and the Capital Region, Buffalo and the Niagara Frontier, Rochester, and Syracuse all offer community splash pads and aquatic centers with free or low-cost access. The Finger Lakes and Hudson Valley regions add more options for families visiting those popular summer tourism areas. The season runs from Memorial Day through Labor Day across most of the state, with New York City spray features sometimes operating longer. Most municipal splash pads in New York are free. Weekday mornings are the best visiting strategy at the most popular locations, which can become very crowded on hot summer weekends."},
    {"name": "North Carolina", "slug": "north-carolina", "abbr": "NC",
     "description": "North Carolina's warm climate, growing population, and strong community parks programs have combined to produce one of the Southeast's better splash pad networks — and the investment is visible from the mountains to the coast. Charlotte leads the state with the most diverse collection of options, with Mecklenburg County Parks and Recreation operating community splash pads and aquatic centers that serve families across the Charlotte metro. The Raleigh-Durham area, driven by the Research Triangle's rapid growth, has seen significant investment in community parks and water play, with Wake County and Durham County facilities complementing city-operated spray features. Greensboro and Winston-Salem in the Piedmont Triad offer community aquatic options that serve the region's urban and suburban families. The mountain region in the west — including communities near Asheville and Boone — has a cooler summer climate and fewer splash pads, but community options do exist and the mountain setting makes water play especially pleasant. Coastal communities like Wilmington and the Crystal Coast attract summer visitors and have splash pad options that reflect their tourism character. The season runs from May through September at most facilities, with the Coastal Plain's hotter climate enabling a longer window. Most municipal splash pads in North Carolina are free of charge. The state's afternoon thunderstorm pattern in summer means mornings are reliably the best time to visit outdoor facilities. Always check with local parks departments for current hours and seasonal schedules."},
    {"name": "North Dakota", "slug": "north-dakota", "abbr": "ND",
     "description": "North Dakota's summers arrive late and depart early, but the warmth they bring — and the relief they offer after a long prairie winter — makes splash pads a genuinely appreciated community amenity across the Peace Garden State. Fargo, the state's largest city and a growing regional hub, leads North Dakota's water play options with community splash pads and aquatic facilities that serve families throughout the Cass County area and draw visitors from surrounding communities. The Fargo-Moorhead metro's size relative to the rest of the state means it has the most developed infrastructure. Bismarck, the state capital, offers community water play through its parks department that serves the south-central North Dakota population. Grand Forks has community aquatic facilities that serve its university town population and the surrounding region. Minot, in the northwest, rounds out the state's major urban centers with water play options suited to its family-oriented community. The season in North Dakota is typically June through August, though July is the heart of the warm season — North Dakota summers can be genuinely hot on the open prairie, with temperatures reaching into the 90s during peak weeks. Most municipal splash pads are free of charge. The shorter season means facilities are particularly well-attended on the hottest days of summer, and weekday visits offer a noticeably more relaxed experience than crowded weekends. Checking local parks department websites before visiting is strongly recommended, as North Dakota facilities have some of the most precise seasonal windows in the country."},
    {"name": "Ohio", "slug": "ohio", "abbr": "OH",
     "description": "Ohio has one of the most impressive splash pad networks in the country, and the depth of the state's aquatic recreation options reflects decades of investment in community parks and recreation. Columbus, the state capital and largest city, offers community splash pads through Columbus Recreation and Parks across multiple neighborhoods, along with the state's most visited aquatic destinations near the Columbus Zoo area. Cincinnati's park system operates spray features in community parks throughout Hamilton County, and the Greater Cincinnati metro's Ohio suburbs in Warren and Butler counties have built modern aquatic facilities with splash pad components. Cleveland's lakefront location on Lake Erie gives the city a distinctive summer culture, and the Greater Cleveland park systems — including the beloved Metroparks — offer water play options distributed across the region. Dayton's Five Rivers MetroParks is particularly well-regarded for its community recreation facilities, including splash pad and aquatic amenities. The northeastern Ohio communities around Akron, Canton, and Youngstown add further depth to the state's network, and the Lake Erie resort corridor around Sandusky brings additional paid water attractions. The season runs from Memorial Day through Labor Day at most Ohio facilities. Ohio summers are genuinely hot and humid, particularly in July and August, when temperatures reach the 90s and heat index values climb higher. Most municipal splash pads are free. The state's sheer density of options means nearly every Ohio family lives within 15 minutes of a water play facility during summer."},
    {"name": "Oklahoma", "slug": "oklahoma", "abbr": "OK",
     "description": "Oklahoma's summers are long, hot, and frequently accompanied by the kind of relentless sun that makes water play essential for outdoor family time. The state has developed a solid collection of splash pads and community aquatic facilities that typically open as early as late April and run through September, capturing a longer season than most Midwestern states. Oklahoma City anchors the state's splash pad network with the most options — the city's parks department operates community spray features in multiple neighborhoods, and surrounding communities including Edmond, Mustang, and Moore have added modern splash pad facilities to their parks systems in recent years. Tulsa, Oklahoma's second-largest city, offers community water play through Tulsa Parks with facilities that serve the metro area and reflect the city's investment in parks and recreation. Norman, home to the University of Oklahoma, has community aquatic options that suit its college-town and family character. Broken Arrow and Owasso, growing Tulsa suburbs, have developed their own splash pad facilities that serve the region's expanding family populations. The season's peak falls in June, July, and August, when Oklahoma temperatures routinely reach into the high 90s and above — summer heat in the state can be intense even by Southern standards. Most municipal splash pads are free. Mornings are the most comfortable visiting window. Sunscreen and water bottles are essential, and checking local parks websites for current hours is recommended before heading out."},
    {"name": "Oregon", "slug": "oregon", "abbr": "OR",
     "description": "Oregon's relationship with water play is shaped by its famously variable climate — the wet western valleys and coast contrast sharply with the dry, hot eastern high desert, and splash pad demand and season length differ dramatically between regions. Portland leads the state with the most splash pad options, and the city's Parks and Recreation bureau operates spray features in community parks throughout the metro, drawing families during the summer dry season that typically runs from July through September. Portland's summers are genuinely warm and sunny, and the arrival of heat drives strong demand for water play in a city that doesn't broadly have air conditioning. Eugene and the southern Willamette Valley share a similar climate pattern, with a pronounced dry season making summer splash pad visits popular and practical. Eastern Oregon communities including Bend and Medford experience hotter, drier summers than the western valleys and have invested in community aquatic facilities that serve their growing populations through a longer warm season. Salem, Oregon's capital, sits in the heart of the Willamette Valley and has community splash pad options through its parks and recreation department. Most municipal splash pads in Oregon are free. The coastal communities west of the Coast Range experience a milder, foggier summer that limits splash pad demand, though some facilities exist. Checking local parks department websites is especially important in Oregon, where the dry season's arrival can shift the practical splash pad season by weeks from one year to the next."},
    {"name": "Pennsylvania", "slug": "pennsylvania", "abbr": "PA",
     "description": "Pennsylvania's geographic breadth — from the Delaware Valley to the Laurel Highlands and Lake Erie shore — means splash pad options span a wide range of settings and seasons. Philadelphia and its surrounding counties lead the state in volume, with the Philadelphia Parks and Recreation department operating free spray features in neighborhood parks across the city and Montgomery, Bucks, Chester, and Delaware counties offering modern community aquatic facilities in their parks systems. Pittsburgh's parks network on the western end of the state includes splash pad features in community parks throughout Allegheny County, and the city's surrounding suburban communities have invested in aquatic recreation that serves the region's family population. Central Pennsylvania communities including Harrisburg, Lancaster, York, and State College offer community splash pads and aquatic centers that serve their respective regions. The Lehigh Valley around Allentown and Bethlehem has a strong community parks program with water play options. The season runs from Memorial Day through Labor Day across most of Pennsylvania, with the Philadelphia area's mid-Atlantic climate making those summer months warm and humid enough to drive consistent demand. Most municipal splash pads in Pennsylvania are free, though some recreation center aquatic facilities charge admission. The state's afternoon summer thunderstorm pattern means mornings are generally the more reliable choice for outdoor water play. Weekday mornings at popular facilities offer the most relaxed visiting experience during peak summer weeks."},
    {"name": "Rhode Island", "slug": "rhode-island", "abbr": "RI",
     "description": "Rhode Island may be the smallest state in the country, but its communities have made room for water play, and the state punches above its weight in community recreation investment relative to its size. Providence, the capital and largest city, anchors Rhode Island's splash pad offerings with spray features in city parks that serve urban families and give residents in the dense city neighborhoods a free water play option during the summer months. Cranston and Warwick, the state's second and third-largest cities, have community parks programs that include splash pads suited to their suburban family populations. North Providence, Woonsocket, and Pawtucket contribute additional options across the northern part of the state. The South County communities near the coast — including South Kingstown and Narragansett — offer water play options that complement the region's beach access, giving families a splash pad alternative on days when the ocean is less appealing. Newport, one of the state's most-visited tourist destinations, has community park amenities including water play features that serve both residents and summer visitors. The season runs from Memorial Day through Labor Day, with July and August being the peak months. Rhode Island's coastal humidity makes summer temperatures feel warmer than the thermometer reads, and a shaded splash pad with nearby seating is a genuine relief on the hottest afternoons. Most municipal splash pads are free of charge. Checking local parks department websites before visiting is the most reliable approach, as hours can vary significantly across Rhode Island's small but active parks network."},
    {"name": "South Carolina", "slug": "south-carolina", "abbr": "SC",
     "description": "South Carolina's long, hot summers and strong community investment in outdoor recreation have produced a splash pad network that spans the state's three distinct geographic regions — the Upstate, Midlands, and Lowcountry. Charleston and the surrounding Lowcountry lead in visibility, with the coastal heat and humidity creating conditions that make water play popular from April through October — one of the longest operational windows in the country. Charleston County's parks system and the city's recreation programs offer community splash pads that serve both residents and the region's substantial summer visitor population. Columbia, the state capital in the Midlands, operates community splash pads through Richland County and city parks departments, with facilities distributed across the metro area. Greenville anchors the Upstate with modern community aquatic facilities that reflect the region's rapid growth and investment in parks infrastructure. Spartanburg and the surrounding communities add to the Upstate's water play options. Myrtle Beach and the Grand Strand attract large numbers of summer visitors, and beach-adjacent parks in the area offer spray features alongside their other amenities. The season across most of South Carolina runs from late April through September, with Lowcountry facilities often opening earlier and staying open later. Most municipal splash pads are free of charge. South Carolina's afternoon thunderstorm season in summer means morning visits are the most reliable choice. Sunscreen, water, and a change of clothes are standard gear for any South Carolina splash pad outing."},
    {"name": "South Dakota", "slug": "south-dakota", "abbr": "SD",
     "description": "South Dakota's communities make the most of their warm summer months with splash pads and aquatic facilities that give families practical relief from the open-plains heat. Sioux Falls, the state's largest city and one of the fastest-growing mid-sized cities in the Midwest, leads the state with the most developed splash pad network — the city's parks and recreation department operates community water play facilities in several parks across the metro, and the quality of Sioux Falls' community parks reflects consistent investment in recreation. Rapid City, the gateway to the Black Hills and Mount Rushmore, offers community aquatic options that serve both year-round residents and summer tourists who visit the western South Dakota region. Aberdeen in the northeast and Watertown serve their surrounding regions with community splash pads that reflect small-city investment in family recreation. Brookings, home to South Dakota State University, has community water play options with a college-town character. The season typically runs from June through August, with July being the warmest month across most of the state. South Dakota summers can bring genuine heat to the eastern plains, with temperatures in Sioux Falls and surrounding communities reaching into the 90s during peak weeks. Most municipal splash pads are free. The Black Hills region experiences somewhat cooler temperatures than the eastern plains, though community facilities there still operate through the summer season. Checking local parks department websites for current hours is recommended, particularly for smaller community facilities that may have limited staffing or specific operating windows."},
    {"name": "Tennessee", "slug": "tennessee", "abbr": "TN",
     "description": "Tennessee's hot, humid summers create sustained demand for water play from one end of the Volunteer State to the other, and the state's communities have built a strong splash pad network that reflects that need. Nashville leads the state in both volume and variety — Metro Nashville Parks operates community splash pads in several city parks, and surrounding Davidson County communities and the rapidly growing suburbs of Williamson and Rutherford counties have invested in modern aquatic facilities that serve the metro area's large family population. Knoxville anchors east Tennessee with community water play through Knox County Parks, with facilities that serve the Knoxville metro and draw families from surrounding communities in the valley. Memphis, on the Mississippi River, offers community splash pads through its parks and recreation department that serve the city's neighborhoods and reflect the long West Tennessee warm season — Memphis's season can stretch from late April into October. Chattanooga, with its outdoor recreation culture and growing downtown, has community water play options that suit the city's character. The Great Smoky Mountains region around Gatlinburg and Pigeon Forge brings a mix of community and commercial water play options that cater to the area's enormous tourism population. The season across most of Tennessee runs from May through September. Most municipal splash pads are free of charge. Tennessee's afternoon thunderstorm pattern means mornings are the most reliable time for outdoor water play. Weekday visits offer noticeably less competition for space than summer weekends."},
    {"name": "Texas", "slug": "texas", "abbr": "TX",
     "description": "Texas has one of the largest and most diverse collections of splash pads in the country, and the state's intense heat — combined with its enormous and family-oriented population — has driven consistent investment in community water play at every scale. Houston leads the state in sheer volume, with the Houston Parks and Recreation Department operating free community splash pads in neighborhood parks throughout the city and Harris County communities adding their own facilities across the metro. Dallas and Fort Worth together anchor North Texas with dozens of splash pads spread across the DFW metroplex, ranging from free neighborhood spray features to elaborate community aquatic centers with multiple water attractions. Austin's parks network has invested in community splash pads that reflect the city's outdoor recreation culture, and surrounding communities in the Austin metro including Round Rock, Cedar Park, and Pflugerville have added modern facilities in recent years. San Antonio's parks system serves one of the country's largest cities with community water play options appropriate to the South Texas heat. El Paso in the far west and Corpus Christi on the Gulf Coast extend the state's splash pad reach into its distinct regional climates. The season in most of Texas runs from March through November, with the peak from May through September when temperatures across the state regularly reach triple digits. Most municipal splash pads are free. Morning visits before 10 a.m. are strongly recommended during the peak summer heat. Sunscreen, water, and shade-seeking are non-negotiable practical habits for Texas summer outings."},
    {"name": "Utah", "slug": "utah", "abbr": "UT",
     "description": "Utah's dry heat along the Wasatch Front makes splash pads one of the most popular warm-weather destinations for families during the summer months. Salt Lake City and its surrounding suburbs — including West Jordan, Sandy, and Murray — feature community splash pads in parks that range from neighborhood-scale spray areas to larger aquatic facilities with multiple water features. Moving south along the Wasatch Front, Provo and Orem offer well-maintained community water play areas that draw families from Utah, Salt Lake, and Summit counties. Farther north, Ogden and the communities of Weber County have invested in public splash pads and spray parks that make the most of Utah's dry, sunny summers. The season along the Wasatch Front typically runs from late May through September, though southern Utah's communities — particularly in St. George and the Washington County area — enjoy a longer warm season that can push splash pad operation from April through October. The combination of desert heat and high-altitude sunshine means sun protection is essential; most veteran Utah splash pad visitors bring sunscreen, hats, and water bottles as standard gear. Many Utah splash pads are free of charge and operated by city parks and recreation departments. Some aquatic centers charge admission for access to pools and slides. Hours and opening dates vary by facility, so checking local parks department websites before visiting is advisable."},
    {"name": "Vermont", "slug": "vermont", "abbr": "VT",
     "description": "Vermont's summer season is genuinely short — communities typically operate splash pads from late June through mid-August — but the enthusiasm families bring to those weeks more than compensates for the compressed calendar. Burlington, the state's largest city and cultural anchor, leads Vermont's water play options with community parks and recreation facilities that include spray features suited to the city's compact, walkable neighborhoods. The Burlington waterfront parks area, with its views of Lake Champlain, provides a particularly appealing setting for outdoor summer recreation. Rutland, in the center of the state, has community aquatic options through its parks and recreation department that serve south-central Vermont families. Montpelier, the small but vibrant state capital, and nearby Barre offer community recreation facilities including water play options appropriate to their size. Stowe and the ski resort communities, which pivot to outdoor summer recreation after the snow melts, attract visitors who find spray features and splash pads in their community parks. Vermont's Green Mountains moderate summer temperatures — the state is generally cooler than southern New England — but genuine summer heat does arrive in July and early August, and when it does, splash pads are among the most popular destinations in any Vermont community. Most municipal splash pads are free of charge, and many are paired with playground equipment and picnic areas that make them a full family outing. Because the season is short, popular facilities fill quickly on the hottest days. Checking local recreation department websites for current hours is essential before visiting."},
    {"name": "Virginia", "slug": "virginia", "abbr": "VA",
     "description": "Virginia's geographic diversity — from the mountains in the west to the Chesapeake Bay in the east — is matched by an equally varied splash pad landscape that serves families across the state through a long and humid summer season. Northern Virginia, in the Washington D.C. suburbs, has the most developed splash pad network in the state. Fairfax County's park authority operates some of the region's best community aquatic facilities, and communities including Arlington, Alexandria, Reston, and Loudoun County have invested in modern splash pads that serve the area's large family population. Richmond, the state capital and a growing mid-sized city, offers community splash pads through Richmond and Henrico County parks programs that serve families across the metro area. Virginia Beach and the Hampton Roads region — including Chesapeake, Norfolk, and Newport News — benefit from the coastal climate and have invested in community aquatic facilities suited to the region's large military and civilian family population. Charlottesville and the Blue Ridge area offer community options appropriate to their size and character. Roanoke serves western Virginia families with community aquatic facilities through its parks department. The season across Virginia runs from May through September, with Northern Virginia's proximity to the D.C. metro's humidity making summer feel intense through August. Most municipal splash pads are free of charge, though some recreation center aquatic facilities charge admission. Mornings are the least crowded and most comfortable visiting time at popular facilities."},
    {"name": "Washington", "slug": "washington", "abbr": "WA",
     "description": "Washington's splash pad season is defined by the state's dramatic west-east climate divide. West of the Cascades, the marine climate of the Puget Sound region keeps summers mild — but the dry season from July through September brings reliable sunshine that makes outdoor water play genuinely popular. Seattle's parks department operates spray features in community parks across the city, and the arrival of summer heat in July sends families to water play options that aren't always needed in the city's mild June. Tacoma, Bellevue, and the broader King and Pierce County communities have invested in community splash pads that serve their large family populations during the Pacific Northwest's distinctive sunny season. East of the Cascades, the climate changes dramatically — Spokane, the Tri-Cities area, and the Yakima Valley experience genuinely hot, dry summers with temperatures regularly exceeding 100 degrees, and the communities there have developed aquatic facilities with longer operational windows that reflect the extended warm season. Spokane in particular has a strong splash pad network for its size, with the Spokane Parks Department operating community water play facilities that serve the region from June through September. Most municipal splash pads in Washington are free of charge. Sunscreen is essential even in the Pacific Northwest, where UV intensity during the dry season can be underestimated. Checking local parks department websites before visiting is important, as Washington facilities have varying seasonal schedules that reflect the region's weather patterns."},
    {"name": "West Virginia", "slug": "west-virginia", "abbr": "WV",
     "description": "West Virginia's mountain communities have embraced splash pads as a summer staple, offering water play areas that provide genuine relief during the warm, humid months from June through August. Charleston, the state capital, anchors the state's water play options with community parks that serve the Kanawha Valley's families, and the city has expanded its outdoor recreation facilities to include updated spray features and aquatic amenities. The Mountain State's geography creates regional variation in summer temperatures: the lower valleys and southern coalfields experience hotter, more humid conditions that make splash pads especially appealing, while the higher elevations of the eastern highlands offer a somewhat cooler summer climate. Communities throughout the state — from Huntington and Parkersburg in the west to Morgantown in the north and Beckley in the south — have developed water play options suited to their local populations. The season typically runs from Memorial Day through Labor Day, with peak demand during the hottest stretches of July and August. Most municipal splash pads in West Virginia are free of charge and operate during park hours. Families visiting the state during summer should also take advantage of West Virginia's state park system, which includes swimming areas and water-adjacent recreation that pair well with a splash pad visit. Checking local parks department websites for current hours and seasonal schedules is recommended before heading out."},
    {"name": "Wisconsin", "slug": "wisconsin", "abbr": "WI",
     "description": "Wisconsin's splash pad landscape spans two very different ends of the water play spectrum — the tight-knit community facilities in city parks across the state, and the Wisconsin Dells, which bills itself as the Waterpark Capital of the World and delivers on that claim with an astonishing concentration of indoor and outdoor water attractions. Milwaukee, the state's largest city, has invested in community spray features distributed across its neighborhood parks, giving urban families free access to water play throughout the metro area. Madison, home to the University of Wisconsin and a city with a strong parks culture, operates community splash pads that serve the Dane County metro and reflect the city's consistent investment in outdoor recreation. Green Bay, Appleton, and Racine round out Wisconsin's major urban centers with their own community aquatic facilities. The Wisconsin Dells area in the central part of the state offers year-round indoor waterpark options through its resort hotels and dedicated parks — a genuine draw for families from across the Midwest. The broader Dells region operates extensive outdoor water attractions during the summer season from late May through September. Community splash pads across Wisconsin are typically free of charge and run from June through August, with July the peak month. Wisconsin summers bring warm, humid conditions that make water play particularly appealing in the inland communities away from Lake Michigan's cooling influence. Weekday visits at community splash pads are noticeably less crowded than weekend afternoons during peak summer."},
    {"name": "Wyoming", "slug": "wyoming", "abbr": "WY",
     "description": "Wyoming's small population and vast open spaces mean splash pads are fewer and farther between than in most states, but the communities that have made the investment treat their facilities as valued public amenities that give families a meaningful cool-down option during the mountain summer. Cheyenne, the state capital and largest city, anchors Wyoming's splash pad network with community aquatic facilities that serve southeast Wyoming families through the summer season — the city's parks and recreation department has invested in water play options that reflect Cheyenne's steady population base. Casper, in the center of the state along the North Platte River, offers community water play through its parks department that serves the surrounding Natrona County population and draws families from central Wyoming. Gillette, the energy industry hub of Campbell County, has community recreation facilities including splash pad amenities suited to its family-oriented workforce population. Laramie, home to the University of Wyoming, offers community aquatic options that serve the college town's student and family population during the summer months. The season across Wyoming typically runs from late June through August, reflecting the state's high-altitude climate — even in summer, Wyoming's nights are cool and the daytime season window is compressed compared to lower-elevation states. Most municipal splash pads are free of charge. Sunscreen is essential at Wyoming's elevations, where clear mountain air provides less UV protection than families may expect. Because options are geographically spread out, verifying facility hours and opening dates before driving is a practical necessity across the state."},
]

# Feature filter categories (used for filter pages and nav)
CATEGORIES = [
    {"name": "Free Admission", "slug": "free-admission", "icon": "🆓",
     "description": "Splash pads with no admission cost",
     "intro": "Free splash pads are one of the best-kept secrets for family fun. Operated by city parks departments and community recreation centers, these facilities offer the same water play experience as paid attractions — ground-level jets, spray nozzles, and interactive features — without any cost. Many are located in public parks with playgrounds, restrooms, and picnic areas, making them a complete family outing at zero cost."},
    {"name": "Best for Toddlers", "slug": "toddlers", "icon": "👶",
     "description": "Gentle water features ideal for toddlers and young children",
     "intro": "Toddler-friendly splash pads feature gentle, low-pressure water jets and shallow ground-level spray areas designed for the youngest visitors. These facilities avoid the high-intensity sprayers and deep water that can overwhelm small children, offering a safe introduction to water play. Many also include shaded seating areas where parents can watch comfortably. If your child is between 1 and 4, these are the splash pads to start with."},
    {"name": "Best for Families", "slug": "families", "icon": "👨‍👩‍👧‍👦",
     "description": "Large splash pads with features for all ages",
     "intro": "Family splash pads offer something for every age — from gentle spray areas for toddlers to high-energy water cannons and dumping buckets for older kids. These larger facilities are designed so siblings of different ages can all play together without anyone being bored or overwhelmed. Many include adjacent playgrounds, picnic areas, and restrooms so families can spend a full morning or afternoon."},
    {"name": "With Shade", "slug": "with-shade", "icon": "⛱️",
     "description": "Splash pads with shaded areas to keep the sun off",
     "intro": "Shade matters — especially at splash pads where kids can spend hours in direct sunlight. These facilities include covered pavilions, shade sails, trees, or other structures that protect visitors from UV exposure. Shaded splash pads are particularly important in southern and desert states where summer sun intensity peaks. Even with shade, sunscreen is still recommended, but having a shaded rest area makes a big difference for both kids and parents."},
    {"name": "With Restrooms", "slug": "with-restrooms", "icon": "🚻",
     "description": "Splash pads that have on-site restrooms",
     "intro": "On-site restrooms are one of those amenities you don't think about until you need them — and at a splash pad with young children, you'll need them. These facilities have dedicated restroom buildings, often including changing areas where families can get into and out of swimwear. It's a practical detail that separates a quick splash from a full outing."},
    {"name": "With Picnic Areas", "slug": "with-picnic-areas", "icon": "🧺",
     "description": "Splash pads near picnic tables or pavilions",
     "intro": "Splash pads with picnic areas let families turn water play into a full outing. Pack a lunch, claim a table, and alternate between eating and splashing without having to leave and come back. Many facilities include shaded pavilions, grills, or nearby concession stands. It's the difference between a 30-minute splash and a three-hour family day."},
    {"name": "Indoor", "slug": "indoor", "icon": "🏠",
     "description": "Year-round indoor water play areas",
     "intro": "Indoor splash pads and water play areas operate year-round regardless of weather or season. These climate-controlled facilities — often found inside recreation centers, resorts, and dedicated waterpark buildings — offer slides, spray features, and pools in a warm, enclosed environment. They're the answer for families in northern states who want water play in January, or for anyone looking to avoid sunburn and rain delays."},
    {"name": "Accessible", "slug": "accessible", "icon": "♿",
     "description": "ADA accessible splash pads and water play areas",
     "intro": "Accessible splash pads are designed so children and adults of all abilities can enjoy water play. These facilities feature ADA-compliant surfaces, wheelchair-accessible spray areas, ground-level jets that don't require climbing or standing, and accessible paths to and from the water play area. Many also include accessible restrooms and parking. Every child deserves to play in the water — these facilities make that possible."},
    {"name": "Amusement Parks", "slug": "amusement-parks", "icon": "🎢",
     "description": "Theme and amusement parks with splash pad and water attractions",
     "intro": "Many of the country's most popular theme and amusement parks include splash pads, spray zones, and dedicated water areas alongside their rides and attractions. These facilities range from themed splash zones designed for younger visitors to full-scale water rides and play areas. They're a great way to cool off between coaster rides and add a water play dimension to a theme park visit."},
    {"name": "Water Parks", "slug": "water-parks", "icon": "🌊",
     "description": "Dedicated water parks and resort water parks with slides and attractions",
     "intro": "Dedicated water parks go well beyond a basic splash pad — they offer water slides, wave pools, lazy rivers, and multi-level splash structures alongside traditional spray features. These are full-day destinations with amenities like locker rooms, concessions, cabana rentals, and lifeguard coverage. Whether it's a community-operated aquatic park or a resort-scale waterpark, these facilities deliver the most complete water play experience available."},
]

# Google Analytics
GA_MEASUREMENT_ID = os.getenv("GA_MEASUREMENT_ID", "")

# MailChimp
# Set to the MailChimp embedded form action URL, e.g.:
#   https://xxxxxx.us1.list-manage.com/subscribe/post?u=XXXXXXXX&id=XXXXXXXX
MAILCHIMP_FORM_URL = os.getenv("MAILCHIMP_FORM_URL", "")

# SEO Settings
DEFAULT_META_TITLE = f"{SITE_NAME} - Find Splash Pads Near You"
DEFAULT_META_DESCRIPTION = SITE_DESCRIPTION

# Build Settings
ITEMS_PER_PAGE = 24
FEATURED_COUNT = 6
RECENT_COUNT = 8
